// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.5
// - protoc             v3.8.0
// source: cart.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartServiceClient interface {
	GetCustomerCart(ctx context.Context, in *GetCustomerCartRequest, opts ...grpc_go.CallOption) (*GetCustomerCartResponse, common.ErrorWithAttachment)
}

type cartServiceClient struct {
	cc *triple.TripleConn
}

type CartServiceClientImpl struct {
	GetCustomerCart func(ctx context.Context, in *GetCustomerCartRequest) (*GetCustomerCartResponse, error)
}

func (c *CartServiceClientImpl) GetDubboStub(cc *triple.TripleConn) CartServiceClient {
	return NewCartServiceClient(cc)
}

func (c *CartServiceClientImpl) XXX_InterfaceName() string {
	return "com.jeongen.fastmall.cart.CartService"
}

func NewCartServiceClient(cc *triple.TripleConn) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) GetCustomerCart(ctx context.Context, in *GetCustomerCartRequest, opts ...grpc_go.CallOption) (*GetCustomerCartResponse, common.ErrorWithAttachment) {
	out := new(GetCustomerCartResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetCustomerCart", in, out)
}

// CartServiceServer is the server API for CartService service.
// All implementations must embed UnimplementedCartServiceServer
// for forward compatibility
type CartServiceServer interface {
	GetCustomerCart(context.Context, *GetCustomerCartRequest) (*GetCustomerCartResponse, error)
	mustEmbedUnimplementedCartServiceServer()
}

// UnimplementedCartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCartServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedCartServiceServer) GetCustomerCart(context.Context, *GetCustomerCartRequest) (*GetCustomerCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerCart not implemented")
}
func (s *UnimplementedCartServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedCartServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedCartServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &CartService_ServiceDesc
}
func (s *UnimplementedCartServiceServer) XXX_InterfaceName() string {
	return "com.jeongen.fastmall.cart.CartService"
}

func (UnimplementedCartServiceServer) mustEmbedUnimplementedCartServiceServer() {}

// UnsafeCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServiceServer will
// result in compilation errors.
type UnsafeCartServiceServer interface {
	mustEmbedUnimplementedCartServiceServer()
}

func RegisterCartServiceServer(s grpc_go.ServiceRegistrar, srv CartServiceServer) {
	s.RegisterService(&CartService_ServiceDesc, srv)
}

func _CartService_GetCustomerCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetCustomerCart", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// CartService_ServiceDesc is the grpc_go.ServiceDesc for CartService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "com.jeongen.fastmall.cart.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "GetCustomerCart",
			Handler:    _CartService_GetCustomerCart_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "cart.proto",
}
